# Generated by Django 5.1.3 on 2024-11-18 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_inquiry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='dateTime',
            new_name='date',
        ),
    ]
